site_name: Orchard Core Documentation
theme: readthedocs

# Repository
repo_name: OrchardCMS/OrchardCore
repo_url: https://github.com/OrchardCMS/OrchardCore
edit_uri: edit/dev/src

# Options
docs_dir: src

extra_css: 
- css/code-tabs.css
- css/extra.css

extra_javascript:
- js/extra.js

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
#  - markdown.extensions.nl2br
  - markdown_fenced_code_tabs:
      template: 'default'

# Page tree
nav:
    - About: index.md
    - Getting started:
        - Create a CMS Web application: docs/getting-started/README.md
        - Create a Theme: docs/getting-started/theme.md
        - Code Generation Templates: docs/templates/README.md
    - Guides:
        - Index: docs/guides/README.md
        - Create a modular application: docs/guides/create-modular-application-mvc/index.md
        - Run code on startup: docs/guides/run-code-on-startup/index.md
        - Create a website: docs/guides/create-cms-application/index.md
        - Add an item to the admin menu: docs/guides/add-admin-menu/index.md
        - Install localization files: docs/guides/install-localization-files/index.md
    - Modules:
        - Contents: docs/modules/Contents/README.md
        - ContentParts: docs/modules/ContentParts/README.md
        - Content Fields: docs/modules/ContentFields/README.md
        - Content Localization: docs/modules/ContentLocalization/README.md
        - Content Preview: docs/modules/ContentPreview/README.md
        - Content Types: docs/modules/ContentTypes/README.md
        - Media: docs/modules/Media/README.md
        - Media Azure: docs/modules/Media.Azure/README.md
        - Menu: docs/modules/Menu/README.md
        - Navigation: docs/modules/Navigation/README.md
        - Indexing: docs/modules/Indexing/README.md
        - SQL: docs/modules/SQL/README.md
        - Lucene: docs/modules/Lucene/README.md
        - Queries: docs/modules/Queries/README.md
        - Taxonomies: docs/modules/Taxonomies/README.md
        - Templates: docs/modules/Templates/README.md
        - Themes: docs/modules/Themes/README.md
        - Liquid: docs/modules/Liquid/README.md
        - Custom Settings: docs/modules/CustomSettings/README.md
        - Widgets: docs/modules/Widgets/README.md
        - Forms: docs/modules/Forms/README.md
        - Admin Menu: docs/modules/AdminMenu/README.md
    - Core:
        - Configuration: docs/core/Configuration/README.md
        - Data: docs/core/Data/README.md
        - Dynamic Cache: docs/modules/DynamicCache/README.md
        - GraphQL: docs/modules/Apis.GraphQL/README.md
        - GraphQL queries: docs/core/Apis.GraphQL.Abstractions/README.md
        - Health Check: docs/modules/HealthChecks/README.md
        - Localization: docs/modules/Localize/README.md
        - Logging Serilog: docs/core/Logging.Serilog/readme.md
        - Modules: docs/core/Modules/README.md
        - OpenId: docs/modules/OpenId/README.md
        - Placement: docs/core/Placement/README.md
        - Recipes: docs/modules/Recipes/README.md
        - Resources: docs/modules/Resources/README.md
        - Roles: docs/modules/Roles/README.md
        - Scripting: docs/modules/Scripting/README.md
        - Setup: docs/modules/Setup/README.md
        - Tenants: docs/modules/Tenants/README.md
        - Workflows: docs/modules/Workflows/README.md
        - DataProtection (Azure Storage): docs/modules/DataProtection.Azure/README.md
    - Authentication:
        - Microsoft: docs/modules/Microsoft.Authentication/README.md
        - Facebook: docs/modules/Facebook/README.md
        - Twitter: docs/modules/Twitter/README.md
        - GitHub: docs/modules/GitHub/README.md
        - Google: docs/modules/Google/README.md
